### ISSUE TITLE
Missing detection of certain bypasses

### ISSUE THREAD

**Issue by Xitro01** [iamj0ker/bypass-403#1]
In some situations (when investigating apps on different port numbers) this script is missing some bypasses.

Example, this is missing the bypass:
403,9  --> http://xxxx:8096/ -H X-Forwarded-For: 127.0.0.1:80
This is what I added myself to make sure it finds it:
200,2860  --> http://xxxx:8096/ -H X-Forwarded-For: 127.0.0.1

**Comment by iamj0ker** [comment]
oh okay. let me look at those cases later.
thank you for the response
