### ISSUE TITLE
command not found writing file body line58

### ISSUE THREAD

**Issue by ramaraf221** [iamj0ker/bypass-403#14]
![image](https://user-images.githubusercontent.com/60566081/229657115-7b2eefa8-101a-464d-a64e-23523754ca8a.png)

**Comment by 188150486** [comment]
> I have the same issue

Brother, have you solved this problem，I have the same issue ,

**Comment by EvilLizard666** [comment]
Not yet

**Comment by iamj0ker** [comment]
Hey @ramaraf221 @188150486 @EvilLizard666,
This is because you don't have the tool **jq** which is a json processor.
To solve this, you can install the tool on linux using `sudo apt install jq`

**Comment by EvilLizard666** [comment]
> Hey @ramaraf221 @188150486 @EvilLizard666, This is because you don't have the tool **jq** which is a json processor. To solve this, you can install the tool on linux using `sudo apt install jq`

I forgot that i was using a new kali installation the previous one i couldn't install jq i don't know why but the new one worked thanks very much
